@startuml

title Caso de Uso Resultado Secante

left to right direction

actor Aplicación as aplication
actor Librería as library

rectangle  {
    usecase "Importar Operación Secante de Librería" as importar
    usecase "Calcular y Devolver Resultado" as calcular

}

aplication --> importar: ""
library --> calcular: ""

@enduml