@startuml
skinparam noteBackgroundColor #f5f5f5
skinparam noteBorderColor #c90000
skinparam arrowColor #218c00
skinparam stateBackgroundColor #faf4b4
skinparam stateBorderColor #c90000
skinparam linetype polyline
skinparam arrowThickness 1

title Diagrama de Contexto Módulo Ecuaciones de una variable

[*] --> WEB
note on link
  Abrir WEB  
end note

State WEB {
[*] --> ECUACIONES_UNA_VARIABLE
note on link
  Listar Módulos y Operaciones  
end note

ECUACIONES_UNA_VARIABLE-d-> BISECCION
note on link
  Abrir Bisección  
end note 

BISECCION -d-> ECUACIONES_UNA_VARIABLE
note on link
  Listar Módulos y Operaciones
end note

BISECCION-D-> BISECCION
note on link
  Crear Operación Bisección 
end note 

ECUACIONES_UNA_VARIABLE-d-> PUNTO_FIJO
note on link
  Abrir Iteración Punto Fijo
end note 

PUNTO_FIJO-d-> ECUACIONES_UNA_VARIABLE
note on link
  Listar Módulos y Operaciones
end note

PUNTO_FIJO-D-> PUNTO_FIJO
note on link
  Crear Operación Punto Fijo
end note 

ECUACIONES_UNA_VARIABLE-d-> NEWTON
note on link
  Abrir Método Newton
end note 

NEWTON-d-> ECUACIONES_UNA_VARIABLE
note on link
  Listar Módulos y Operaciones
end note

NEWTON-D-> NEWTON
note on link
  Crear Operación Newton
end note 

ECUACIONES_UNA_VARIABLE-d-> SECANTE
note on link
  Abrir Método Secante
end note 

SECANTE-d-> ECUACIONES_UNA_VARIABLE
note on link
  Listar Módulos y Operaciones
end note

SECANTE-D-> SECANTE
note on link
  Crear Operación Secante
end note 

ECUACIONES_UNA_VARIABLE-d-> FALSA_POSICION
note on link
  Abrir Método Falsa Posición
end note 

FALSA_POSICION-d-> ECUACIONES_UNA_VARIABLE
note on link
  Listar Módulos y Operaciones
end note

FALSA_POSICION-D-> FALSA_POSICION
note on link
  Crear Operación Falsa Posición
end note 

ECUACIONES_UNA_VARIABLE-d-> STEFFENSEN
note on link
  Abrir Método Steffensen
end note 

STEFFENSEN-d-> ECUACIONES_UNA_VARIABLE
note on link
  Listar Módulos y Operaciones
end note

STEFFENSEN-D-> STEFFENSEN
note on link
  Crear Operación Steffensen
end note 

ECUACIONES_UNA_VARIABLE-d-> HORNER
note on link
  Abrir Método Horner
end note 

HORNER-d-> ECUACIONES_UNA_VARIABLE
note on link
  Listar Módulos y Operaciones
end note

HORNER-D-> HORNER
note on link
  Crear Operación Horner
end note 

ECUACIONES_UNA_VARIABLE-d-> MÜLLER
note on link
  Abrir Método Müller
end note 

MÜLLER-d-> ECUACIONES_UNA_VARIABLE
note on link
  Listar Módulos y Operaciones
end note

MÜLLER-D-> MÜLLER
note on link
  Crear Operación Müller
end note 
}

WEB --> [*]
note on link
  Cerrar WEB
end note

@enduml