@startuml

title Caso de Uso Resultado Regla Trapezoidal Compuesta

left to right direction

actor Aplicación as aplication
actor Librería as library

rectangle  {
    usecase "Importar Operación Regla Trapezoidal Compuesta de Librería" as importar
    usecase "Calcular y Devolver Resultado" as calcular

}

aplication --> importar: ""
library --> calcular: ""

@enduml