@startuml

title Caso de Uso Resultado Newton Cotes Abierto n=1

left to right direction

actor Aplicación as aplication
actor Librería as library

rectangle  {
    usecase "Importar Operación Newton Cotes Abierto n=1 de Librería" as importar
    usecase "Calcular y Devolver Resultado" as calcular

}

aplication --> importar: ""
library --> calcular: ""

@enduml