@startuml

title Caso de Uso Resultado Extremo de 5 Puntos

left to right direction

actor Aplicación as aplication
actor Librería as library

rectangle  {
    usecase "Importar Operación Extremo de 5 Puntos de Librería" as importar
    usecase "Calcular y Devolver Resultado" as calcular

}

aplication --> importar: ""
library --> calcular: ""

@enduml