@startuml

skinparam state {
  BackgroundColor #faf4b4
  BorderColor #c90000
}

skinparam note {
  BackgroundColor #f5f5f5
}

skinparam linetype polyline

title Detalle Caso de Uso Resultado Newton Cotes Cerrado n=2

RESULTADO_NEWTON_COTES_C2-[#green]-> :libreria
note on link
  **Aplicación solicita:**
  - Importar método newton cotes cerrrado n=2
end note

:libreria -[#green]-> :abrir_resultado_newton_cotes_c2
note on link
  **Librería realiza:**
  - Calcular operación newton cotes cerrado n=2
  - Devolver resultado
end note

:abrir_resultado_newton_cotes_c2-[#green]-> NEWTON_COTES_C2

@enduml