@startuml

top to bottom direction

skinparam state {
  BackgroundColor #faf4b4
  BorderColor #c90000
}

skinparam note {
  BackgroundColor #f5f5f5
}

skinparam linetype polyline

title Detalle Caso de Uso Crear Operación Newton Cotes Cerrado n=4

state NEWTON_COTES_C4

NEWTON_COTES_C4-[#green]-> crear_newton_cotes_c4
note on link
  **Cliente solicita:**
  - Crear operación newton cotes cerrado n=4
end note

state crear_newton_cotes_c4{
  state 1 as " "
  state 2 as " "
  state 3 as " "
  
  [*] -[#green]-> 1
  1 -[#green]-> 2
  note on link
      **Sistema requiere Parámetros:**
      - funcion
      - a
      - b
  end note
  2 -[#green]-> 3
  note on link
    **Cliente Proporciona Parámetros:**
      - funcion
      - a
      - b
  end note
  3 -[#red]-> 1
  note on link
    [Parámetros 
      Inválidos]
  end note
  3 -[#green]-> [*]

}

crear_newton_cotes_c4-[#green]-> :calcularResultadoNewtonCotesC4

:calcularResultadoNewtonCotesC4-[#green]-> NEWTON_COTES_C4

@enduml