@startuml

skinparam state {
  BackgroundColor #faf4b4
  BorderColor #c90000
}

skinparam note {
  BackgroundColor #f5f5f5
}

skinparam linetype polyline

title Detalle Caso de Uso Abrir Newton Cotes Abierto n=2


DIFERENCIACION_NUMERICA_E_INTEGRACION-[#green]-> abrir_newton_cotes_a2
note on link
  **Usuario solicita:**
  - Abrir Newton Cotes Abierto n=2
end note

state abrir_newton_cotes_a2{
  state 1 as " "
  state 2 as " "
  state 3 as " "
  
  [*] -[#green]-> 1
  1 -[#green]-> 2
  note on link
      **Sistema requiere:**
      - Método newton cotes abierto n=2 conocido
  end note
  2 -[#green]-> 3
  note on link
    **Usuario Selecciona:**
    - Método newton cotes abierto n=2 conocido
  end note
 
  3 -[#green]-> [*]
}

abrir_newton_cotes_a2-[#green]-> :abrirNewtonCotesA2

:abrirNewtonCotesA2-[#green]-> NEWTON_COTES_A2

@enduml