@startuml

skinparam state {
  BackgroundColor #faf4b4
  BorderColor #c90000
}

skinparam note {
  BackgroundColor #f5f5f5
}

skinparam linetype polyline

title Detalle Caso de Uso Abrir Regla Punto Medio Compuesta


DIFERENCIACION_NUMERICA_E_INTEGRACION-[#green]-> abrir_punto_medio_compuesta
note on link
  **Cliente solicita:**
  - Abrir Regla Punto Medio Compuesta
end note

state abrir_punto_medio_compuesta{
  state 1 as " "
  state 2 as " "
  state 3 as " "
  
  [*] -[#green]-> 1
  1 -[#green]-> 2
  note on link
      **Sistema requiere:**
      - Método punto medio compuesto conocido
  end note
  2 -[#green]-> 3
  note on link
    **Cliente Selecciona:**
    - Método punto medio compuesto conocido
  end note
 
  3 -[#green]-> [*]
}

abrir_punto_medio_compuesta-[#green]-> :abrirPuntoMedioCompuesta

:abrirPuntoMedioCompuesta-[#green]-> PUNTO_MEDIO_COMPUESTA

@enduml