@startuml

skinparam state {
  BackgroundColor #faf4b4
  BorderColor #c90000
}

skinparam note {
  BackgroundColor #f5f5f5
}

skinparam linetype polyline

title Detalle Caso de Uso Abrir Integración de Romberg


DIFERENCIACION_NUMERICA_E_INTEGRACION-[#green]-> abrir_integracion_romberg
note on link
  **Usuario solicita:**
  - Abrir Integración de Romberg
end note

state abrir_integracion_romberg{
  state 1 as " "
  state 2 as " "
  state 3 as " "
  
  [*] -[#green]-> 1
  1 -[#green]-> 2
  note on link
      **Sistema requiere:**
      - Método integración romberg conocido
  end note
  2 -[#green]-> 3
  note on link
    **Usuario Selecciona:**
    - Método integración romberg conocido
  end note
 
  3 -[#green]-> [*]
}

abrir_integracion_romberg-[#green]-> :abrirIntegracionRomberg

:abrirIntegracionRomberg-[#green]-> INTEGRACION_ROMBERG

@enduml