@startuml

skinparam state {
  BackgroundColor #faf4b4
  BorderColor #c90000
}

skinparam note {
  BackgroundColor #f5f5f5
}

skinparam linetype polyline

title Detalle Caso de Uso Abrir Punto Medio 2º Derivada


DIFERENCIACION_NUMERICA_E_INTEGRACION-[#green]-> abrir_punto_medio_2_derivada
note on link
  **Usuario solicita:**
  - Abrir Punto Medio 2º Derivada
end note

state abrir_punto_medio_2_derivada{
  state 1 as " "
  state 2 as " "
  state 3 as " "
  
  [*] -[#green]-> 1
  1 -[#green]-> 2
  note on link
      **Sistema requiere:**
      - Método punto medio 2º derivada conocido
  end note
  2 -[#green]-> 3
  note on link
    **Usuario Selecciona:**
    - Método punto medio 2º derivada conocido
  end note
 
  3 -[#green]-> [*]
}

abrir_punto_medio_2_derivada-[#green]-> :abrirPuntoMedio2Derivada

:abrirPuntoMedio2Derivada-[#green]-> PUNTO_MEDIO_2_DERIVADA

@enduml