@startuml

skinparam state {
  BackgroundColor #faf4b4
  BorderColor #c90000
}

skinparam note {
  BackgroundColor #f5f5f5
}

skinparam linetype polyline

title Detalle Caso de Uso Resultado Regla Trapzoidal Compuesta

RESULTADO_TRAPEOIDAL_COMPUESTA-[#green]-> :libreria
note on link
  **Aplicación solicita:**
  - Importar método trapezoidal compuesta
end note

:libreria -[#green]-> :abrir_resultado_trapezoidal_compuesta
note on link
  **Librería realiza:**
  - Calcular operación trapezoidal compuesta
  - Devolver resultado
end note

:abrir_resultado_trapezoidal_compuesta-[#green]-> TRAPEZOIDAL_COMPUESTA

@enduml