@startuml

skinparam state {
  BackgroundColor #faf4b4
  BorderColor #c90000
}

skinparam note {
  BackgroundColor #f5f5f5
}

skinparam linetype polyline

title Detalle Caso de Uso Abrir Newton Cotes Cerrado n=2


DIFERENCIACION_NUMERICA_E_INTEGRACION-[#green]-> abrir_newton_cotes_c2
note on link
  **Usuario solicita:**
  - Abrir Newton Cotes Cerrado n=2
end note

state abrir_newton_cotes_c2{
  state 1 as " "
  state 2 as " "
  state 3 as " "
  
  [*] -[#green]-> 1
  1 -[#green]-> 2
  note on link
      **Sistema requiere:**
      - Método newton cotes cerrado n=2 conocido
  end note
  2 -[#green]-> 3
  note on link
    **Usuario Selecciona:**
    - Método newton cotes cerrado n=2 conocido
  end note
 
  3 -[#green]-> [*]
}

abrir_newton_cotes_c2-[#green]-> :abrirNewtonCotesC2

:abrirNewtonCotesC2-[#green]-> NEWTON_COTES_C2

@enduml