@startuml

top to bottom direction

skinparam state {
  BackgroundColor #faf4b4
  BorderColor #c90000
}

skinparam note {
  BackgroundColor #f5f5f5
}

skinparam linetype polyline

title Detalle Caso de Uso Crear Operación Punto Medio 2º Derivada

state PUNTO_MEDIO_2_DERIVADA 

PUNTO_MEDIO_2_DERIVADA -[#green]-> crear_punto_medio_2_derivada_funcion
note on link
  **Cliente solicita:**
  - Crear operación punto medio 2º derivada
  **Cliente elige:**
  - Función de entrada
end note
PUNTO_MEDIO_2_DERIVADA -[#green]-> crear_punto_medio_2_derivada_datos
note on link
  **Cliente solicita:**
  - Crear operación punto medio 2º derivada
  **Cliente elige:**
  - Conjunto de datos de entrada
end note

state crear_punto_medio_2_derivada_funcion{
  state 1 as " "
  state 2 as " "
  state 3 as " "
  
  [*] -[#green]-> 1
  1 -[#green]-> 2
  note on link
      **Sistema requiere Parámetros:**
      - funcion
      - x0
      - h
  end note
  2 -[#green]-> 3
  note on link
    **Cliente Proporciona Parámetros:**
      - funcion
      - x0
      - h
  end note
  3 -[#red]-> 1
  note on link
    [Parámetros 
      Inválidos]
  end note
  3 -[#green]-> [*]

}

state crear_punto_medio_2_derivada_datos {
  state 4 as " "
  state 5 as " "
  state 6 as " "
  
  [*] -[#green]-> 4
  4 -[#green]-> 5
  note on link
      **Sistema requiere Parámetros:**
      - datos
      - x0
  end note
  5 -[#green]-> 6
  note on link
    **Cliente Proporciona Parámetros:**
      - datos
      - x0
  end note
  6 -[#red]-> 4
  note on link
    [Parámetros 
     Inválidos]
  end note
  6 -[#green]-> [*]

}


crear_punto_medio_2_derivada_funcion -[#green]-> :calcularResultadoPuntoMedio2Derivada
crear_punto_medio_2_derivada_datos -[#green]-> :calcularResultadoPuntoMedio2Derivada

:calcularResultadoPuntoMedio2Derivada-[#green]-> PUNTO_MEDIO_2_DERIVADA 

@enduml