@startuml

skinparam state {
  BackgroundColor #faf4b4
  BorderColor #c90000
}

skinparam note {
  BackgroundColor #f5f5f5
}

skinparam linetype polyline

title Detalle Caso de Uso Resultado Bisección

RESULTADO_BISECCION-[#green]-> :libreria
note on link
  **Aplicación solicita:**
  - Importar método bisección
end note

:libreria -[#green]-> :abrir_resultado_biseccion
note on link
  **Librería realiza:**
  - Calcular operación de bisección
  - Devolver resultado
end note

:abrir_resultado_biseccion -[#green]-> BISECCION

@enduml