@startuml

skinparam packageBorderColor white
skinparam packageBackgroundColor white

title Diagrama de Objetos de la Operación Regla de Simpson Compuesta

package " " {
  object "aplicación: numath_API" as flask_app {
    create_app() : numath_API
  }
  
  object "diferenciacion_numerica_e_integracion_controller: regla de simpson compuesta" as operaciones {
    composite_simpson_rule_endpoint("sin(x)", "0", "pi", "100")  
  }
}

node "Librería Numath" as PyLibrary {
}

flask_app -- operaciones: "Cliente solicita operación simpson compuesta >"
operaciones -- PyLibrary : "LLama a >"
operaciones -- flask_app : "Devuelve resultado >"

@enduml