@startuml
title Diagrama de Clases

skinparam packageBorderColor white
skinparam packageBackgroundColor white

package " " {
  class __init__ {
  }

  class ecuaciones_una_variable_controller {
  }

  class diferenciacion_numerica_e_integracion_controller {
  }
}

node "Librería Numath" as PyLibrary {
}

__init__ --> ecuaciones_una_variable_controller : "Cliente solicita una operación"
__init__ --> diferenciacion_numerica_e_integracion_controller: "Cliente solicita una operación"

ecuaciones_una_variable_controller --> PyLibrary : "Llama a"
diferenciacion_numerica_e_integracion_controller --> PyLibrary : "Llama a"

ecuaciones_una_variable_controller --> __init__ : "Devuelve resultado"
diferenciacion_numerica_e_integracion_controller --> __init__ : "Devuelve resultado"

@enduml

