@startuml
skinparam noteBackgroundColor #f5f5f5
skinparam noteBorderColor #c90000
skinparam arrowColor #218c00
skinparam stateBackgroundColor #faf4b4
skinparam stateBorderColor #c90000
skinparam linetype polyline
skinparam arrowThickness 1

title Diagrama de Contexto General

[*] --> WEB
note on link
  Abrir WEB  
end note

State WEB {
[*] --> ESTADO_PRINCIPAL
note on link
  Listar Módulos y Operaciones
end note

ESTADO_PRINCIPAL-d-> OPERACION 
note on link
  Abrir Operación
end note 

OPERACION -d-> ESTADO_PRINCIPAL
note on link
  Listar Módulos y Operaciones
end note

OPERACION -D-> OPERACION 
note on link
  Crear Operación  
end note 


}

WEB --> [*]
note on link
  Cerrar WEB
end note

@enduml