@startuml

skinparam state {
  BackgroundColor #faf4b4
  BorderColor #c90000
}

skinparam note {
  BackgroundColor #f5f5f5
}

skinparam linetype polyline

title Detalle Caso de Uso Resultado Falsa Posición

RESULTADO_FALSA_POSICION-[#green]-> :libreria
note on link
  **Aplicación solicita:**
  - Importar método falsa posición
end note

:libreria -[#green]-> :abrir_resultado_falsa_posicion
note on link
  **Librería realiza:**
  - Calcular operación de falsa posición
  - Devolver resultado
end note

:abrir_resultado_falsa_posicion -[#green]-> FALSA_POSICION

@enduml