@startuml

skinparam state {
  BackgroundColor #faf4b4
  BorderColor #c90000
}

skinparam note {
  BackgroundColor #f5f5f5
}

skinparam linetype polyline

title Detalle Caso de Uso Resultado Steffensen

RESULTADO_STEFFENSEN-[#green]-> :libreria
note on link
  **Aplicación solicita:**
  - Importar método steffensen
end note

:libreria -[#green]-> :abrir_resultado_steffensen
note on link
  **Librería realiza:**
  - Calcular operación de steffensen
  - Devolver resultado
end note

:abrir_resultado_steffensen -[#green]-> STEFFENSEN

@enduml