@startuml

skinparam state {
  BackgroundColor #faf4b4
  BorderColor #c90000
}

skinparam note {
  BackgroundColor #f5f5f5
}

skinparam linetype polyline

title Detalle Caso de Uso Crear Operación Newton


NEWTON -[#green]-> crear_newton 
note on link
  **Usuario solicita:**
  - Crear operación newton
end note

state crear_newton {
  state 1 as " "
  state 2 as " "
  state 3 as " "
  
  [*] -[#green]-> 1
  1 -[#green]-> 2
  note on link
      **Sistema requiere Parámetros:**
      - funcion
      - p0
      - TOL
      - N0
      - factor
  end note
  2 -[#green]-> 3
  note on link
    **Usuario Proporciona Parámetros:**
      - funcion
      - p0
      - TOL
      - N0
      - factor
  end note
  3 -[#red]-> 1
  note on link
    [Parámetros Inválidos]
  end note
  3 -[#green]-> [*]
}

crear_newton -[#green]-> :abrirResultadoNewton

:abrirResultadoNewton -[#green]-> RESULTADO_NEWTON

@enduml