@startuml

skinparam state {
  BackgroundColor #faf4b4
  BorderColor #c90000
}

skinparam note {
  BackgroundColor #f5f5f5
}

skinparam linetype polyline

title Detalle Caso de Uso Abrir Método Newton


ECUACIONES_UNA_VARIABLE -[#green]-> abrir_newton
note on link
  **Usuario solicita:**
  - Abrir Método Newton
end note

state abrir_newton{
  state 1 as " "
  state 2 as " "
  state 3 as " "
  
  [*] -[#green]-> 1
  1 -[#green]-> 2
  note on link
      **Sistema requiere:**
      - Método newton conocido
  end note
  2 -[#green]-> 3
  note on link
    **Usuario Selecciona:**
    - Método newton conocido
  end note
 
  3 -[#green]-> [*]
}

abrir_newton-[#green]-> :abrirNewton

:abrirNewton -[#green]-> NEWTON

@enduml